/* test_ops.c - fixture-driven validation of the individual Kimi K3 kernels.
 *
 * Each fixture under tests/fixtures/ops/ is generated by tools/emit_fixtures.py from the
 * pure-torch reference and carries its own weights, inputs and expected outputs. This
 * binary reads them and reports pass or fail per operation.
 *
 * Per-op fixtures exist alongside the full-model oracle because the oracle localises
 * nothing: it reports that the stack is wrong, not which of ~40 kernels is responsible.
 * Every kernel is gated here individually so a failure names its own cause.
 *
 * Fixtures are parsed with the vendored json.h (Apache 2.0, see NOTICE).
 */
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "json.h"
#include "k3.h"

/* FALLBACKS ONLY. The authority is the tolerance block in MANIFEST.json, loaded by main
 * and applied to every comparison. These values are used only if the manifest cannot be
 * read, and they are deliberately looser than the published contract so that the
 * fallback can never be mistaken for a pass at the real tolerance.
 *
 * Tolerances live in the manifest rather than in this file so the fixture set and its
 * pass criteria cannot drift apart. A harness that grades itself more kindly than its
 * own manifest is worse than no manifest at all. */
static float ATOL = 1e-4f;
static float RTOL = 1e-3f;

static int g_pass = 0, g_fail = 0;
/* Skips are counted and surfaced in the summary. A test whose fixture is absent prints
 * returned without touching either counter, so the summary still read "21 passed, 0
 * failed" with a test silently missing. For t_mxfp4 that meant the ONLY check of the
 * expert quantisation format against released checkpoint bytes could vanish and the suite
 * would still report a clean sweep. Skips are now counted and are a non-zero exit. */
static int g_skip = 0;

/* ------------------------------------------------------------- utilities ---- */
static char *slurp(const char *path)
{
    FILE *f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "cannot open %s\n", path); return NULL; }
    fseek(f, 0, SEEK_END); long n = ftell(f); fseek(f, 0, SEEK_SET);
    char *b = (char *)malloc((size_t)n + 1);
    if (!b) { fclose(f); return NULL; }
    if (fread(b, 1, (size_t)n, f) != (size_t)n) { free(b); fclose(f); return NULL; }
    b[n] = 0; fclose(f);
    return b;
}

/* like slurp but silent, for optional fixtures whose absence is not an error */
static char *slurp_quiet(const char *path)
{
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END); long n = ftell(f); fseek(f, 0, SEEK_SET);
    char *b = (char *)malloc((size_t)n + 1);
    if (!b || fread(b, 1, (size_t)n, f) != (size_t)n) { free(b); fclose(f); return NULL; }
    b[n] = 0; fclose(f);
    return b;
}

/* pull "key": {"shape": [...], "data": [...]} into a freshly allocated float array */
static float *arr(jval *root, const char *key, int *count)
{
    jval *o = json_get(root, key);
    if (!o) { fprintf(stderr, "  missing key %s\n", key); return NULL; }
    jval *d = (o->t == J_OBJ) ? json_get(o, "data") : o;
    if (!d || d->t != J_ARR) { fprintf(stderr, "  key %s has no data array\n", key); return NULL; }
    float *v = (float *)malloc((size_t)d->len * sizeof(float));
    if (!v) return NULL;
    for (int i = 0; i < d->len; i++) v[i] = (float)d->kids[i]->num;
    if (count) *count = d->len;
    return v;
}

static double num(jval *root, const char *key, double dflt)
{
    jval *v = json_get(root, key);
    return (v && v->t == J_NUM) ? v->num : dflt;
}

/* JSON booleans are J_BOOL, not J_NUM. Reading one with num() silently yields the
 * default, which is how layer_mla was first mistaken for a KDA layer and asked for
 * weights it does not have. */
static int boolean(jval *root, const char *key, int dflt)
{
    jval *v = json_get(root, key);
    if (!v) return dflt;
    if (v->t == J_BOOL) return v->boolean;
    if (v->t == J_NUM)  return (int)v->num;
    return dflt;
}

/* read "key": {"shape": [...]} into dims[]; returns the rank, or 0 if absent.
 * Guessing row counts from element totals is how the first version of this file
 * went wrong; the fixtures carry the shape, so use it. */
static int shape(jval *root, const char *key, int *dims, int maxd)
{
    jval *o = json_get(root, key);
    if (!o || o->t != J_OBJ) return 0;
    jval *s = json_get(o, "shape");
    if (!s || s->t != J_ARR) return 0;
    const int r = s->len < maxd ? s->len : maxd;
    for (int i = 0; i < r; i++) dims[i] = (int)s->kids[i]->num;
    return r;
}

static void report(const char *name, const float *got, const float *want, int n)
{
    double worst = 0.0; int at = -1;
    for (int i = 0; i < n; i++) {
        const double a = fabs((double)got[i] - (double)want[i]);
        const double tol = ATOL + RTOL * fabs((double)want[i]);
        if (a / tol > worst) { worst = a / tol; at = i; }
    }
    if (worst <= 1.0) {
        printf("  PASS  %-14s n=%-6d worst=%.2fx tol\n", name, n, worst);
        g_pass++;
    } else {
        printf("  FAIL  %-14s n=%-6d worst=%.2fx tol at i=%d  got %.7f want %.7f\n",
               name, n, worst, at, got[at], want[at]);
        g_fail++;
    }
}

/* ----------------------------------------------------------------- tests ---- */
static void t_rmsnorm(const char *dir)
{
    char p[512]; snprintf(p, sizeof(p), "%s/rmsnorm.json", dir);
    char *txt = slurp(p); if (!txt) { g_fail++; return; }
    char *ar = NULL; jval *r = json_parse(txt, &ar);
    int nw, ni, no;
    float *w = arr(r, "weight", &nw), *x = arr(r, "in", &ni), *e = arr(r, "out", &no);
    const float eps = (float)num(r, "eps", 1e-5);
    if (w && x && e) {
        const int rows = ni / nw;
        float *y = (float *)malloc((size_t)ni * sizeof(float));
        for (int i = 0; i < rows; i++) k3_rmsnorm(y + i * nw, x + i * nw, w, nw, eps);
        report("rmsnorm", y, e, no);
        free(y);
    }
    free(w); free(x); free(e); free(txt); free(ar);
}

static void t_situ(const char *dir)
{
    char p[512]; snprintf(p, sizeof(p), "%s/situ_glu.json", dir);
    char *txt = slurp(p); if (!txt) { g_fail++; return; }
    char *ar = NULL; jval *r = json_parse(txt, &ar);
    int ni, no;
    float *x = arr(r, "in", &ni), *e = arr(r, "out", &no);
    const float b1 = (float)num(r, "beta", 4.0), b2 = (float)num(r, "linear_beta", 25.0);
    int din[4] = {0}, dout[4] = {0};
    const int rin = shape(r, "in", din, 4), rout = shape(r, "out", dout, 4);
    if (x && e && rin == 2 && rout == 2) {
        const int R = dout[0];        /* rows                              */
        const int W = dout[1];        /* output width; input row is 2*W    */
        if (din[1] != 2 * W || din[0] != R) {
            printf("  FAIL  situ_glu       shape mismatch: in=[%d,%d] out=[%d,%d], "
                   "expected in=[%d,%d]\n", din[0], din[1], R, W, R, 2 * W);
            g_fail++;
            free(x); free(e); free(txt); free(ar);
            return;
        }
        float *y = (float *)malloc((size_t)no * sizeof(float));
        for (int i = 0; i < R; i++)
            k3_situ_glu(y + i * W, x + i * 2 * W, W, b1, b2);
        report("situ_glu", y, e, no);
        /* The soft cap is the one property SiTU-GLU guarantees: |out| <= b1*b2, for any
         * input whatsoever. Violating it means a tanh was dropped or applied to the
         * wrong operand, so this counts as a failure rather than printing a warning
         * nothing acts on. */
        float mx = 0.f; for (int i = 0; i < no; i++) if (fabsf(y[i]) > mx) mx = fabsf(y[i]);
        const int bound_ok = (mx <= b1 * b2 + 1e-2f);
        printf("        bound check |out|=%.3f must be <= b1*b2=%.1f : %s\n",
               mx, b1 * b2, bound_ok ? "ok" : "VIOLATED");
        if (!bound_ok) {
            printf("        SiTU-GLU's soft cap does not hold, a tanh is missing or "
                   "applied to the wrong operand\n");
            g_fail++;
        }
        free(y);
    }
    free(x); free(e); free(txt); free(ar);
}

static void t_shortconv(const char *dir)
{
    char p[512]; snprintf(p, sizeof(p), "%s/shortconv.json", dir);
    char *txt = slurp(p); if (!txt) { g_fail++; return; }
    char *ar = NULL; jval *r = json_parse(txt, &ar);
    int nw, ni, no, ns;
    float *w = arr(r, "weight", &nw), *x = arr(r, "in", &ni), *e = arr(r, "out", &no);
    float *st = arr(r, "state_after", &ns);
    int nxi, nxo;
    float *xn = arr(r, "in_next", &nxi), *en = arr(r, "out_next", &nxo);
    const int K = (int)num(r, "kernel", 4), C = (int)num(r, "channels", 0);
    if (w && x && e && C) {
        const int T = ni / C;
        float *y = (float *)malloc((size_t)ni * sizeof(float));
        float *s = (float *)calloc((size_t)C * (K - 1), sizeof(float));
        k3_shortconv(y, x, w, s, C, K, T);
        report("shortconv", y, e, no);
        if (st) report("conv_state", s, st, ns);

        /* CONTINUATION. Both checks above start from a zero state, so they say nothing
         * about whether k3_shortconv READS the state it was handed. A version that wrote
         * state_after correctly but ignored the incoming history passed all of them, and
         * would then be wrong for every decode step after the first. The fixture has
         * carried this continuation pair all along and no test used it: feed the state
         * from the first call straight into a second call over in_next, and require
         * out_next. This is the only check in the suite that can see the read side. */
        if (xn && en) {
            const int T2 = nxi / C;
            float *y2 = (float *)malloc((size_t)nxi * sizeof(float));
            k3_shortconv(y2, xn, w, s, C, K, T2);   /* s carries forward, deliberately */
            report("conv_continuation", y2, en, nxo);
            free(y2);
        } else {
            printf("  FAIL  conv_continuation  fixture lacks in_next/out_next\n");
            g_fail++;
        }
        free(y); free(s);
    }
    free(w); free(x); free(e); free(st); free(xn); free(en); free(txt); free(ar);
}

static void t_decay(const char *dir)
{
    char p[512]; snprintf(p, sizeof(p), "%s/kda_decay.json", dir);
    char *txt = slurp(p); if (!txt) { g_fail++; return; }
    char *ar = NULL; jval *r = json_parse(txt, &ar);
    int na, nb, ng, nal, nz;
    float *A = arr(r, "A_log", &na), *dt = arr(r, "dt_bias", &nb);
    float *eg = arr(r, "g", &ng), *ea = arr(r, "alpha", &nal);
    float *z  = arr(r, "z", &nz);
    const float lb = (float)num(r, "lower_bound", -5.0);
    /* Drive the engine's own decay kernel and compare its output to torch elementwise.
     *
     * The weaker test this replaces only checked that the fixture's g values lay inside
     * (e^lb, 1]. That is a statement about the FIXTURE, not about the C: a k3_kda_decay
     * indexing A_log per channel instead of per head, or ignoring dt_bias entirely,
     * satisfies the range check. Exporting z lets the real function run forward from the
     * same inputs, which is the only version of this test that can fail. */
    if (A && dt && eg && ea && z) {
        const int H = na, D = nb / na, tok = ng / nb;
        float *gc = (float *)malloc((size_t)ng * sizeof(float));
        float *ac = (float *)malloc((size_t)nal * sizeof(float));
        double wg = 0.0, wa = 0.0;
        for (int t = 0; t < tok; t++)
            k3_kda_decay(gc + (size_t)t * nb, ac + (size_t)t * nb,
                         z + (size_t)t * nb, A, dt, H, D, lb);
        for (int i = 0; i < ng; i++) {
            const double dg = fabs((double)gc[i] - eg[i]);
            const double da = fabs((double)ac[i] - ea[i]);
            if (dg > wg) wg = dg;
            if (da > wa) wa = da;
        }
        /* A_log spans linspace(-0.4, 1.2) across heads, so a per-CHANNEL misindex moves
         * every element and shows up here immediately. */
        const int ok = (wg <= 1e-5) && (wa <= 1e-5);
        printf("  %s  kda_decay      H=%d D=%d tok=%d  max|dg|=%.3e max|dalpha|=%.3e "
               "(drives k3_kda_decay)\n", ok ? "PASS" : "FAIL", H, D, tok, wg, wa);
        if (ok) g_pass++; else g_fail++;
        free(gc); free(ac);
    } else {
        printf("  FAIL  kda_decay      fixture missing a required field%s\n",
               z ? "" : " (z absent: regenerate with tools/emit_fixtures.py)");
        g_fail++;
    }
    free(A); free(dt); free(eg); free(ea); free(z); free(txt); free(ar);
}

static void t_attnres(const char *dir)
{
    char p[512]; snprintf(p, sizeof(p), "%s/attnres.json", dir);
    char *txt = slurp(p); if (!txt) { g_fail++; return; }
    char *ar = NULL; jval *r = json_parse(txt, &ar);
    int npx, nbr, nf, no;
    float *px = arr(r, "prefix_sum", &npx), *br = arr(r, "block_residual", &nbr);
    float *fold = arr(r, "fold_hint", &nf), *e = arr(r, "out", &no);
    const float eps = (float)num(r, "eps", 1e-5);
    if (px && br && fold && e) {
        const int n = nf, rows = npx / n, nblk = nbr / (rows * n);
        const int nsrc = nblk + 1;
        float *src = (float *)malloc((size_t)nsrc * n * sizeof(float));
        float *y = (float *)malloc((size_t)rows * n * sizeof(float));
        for (int rw = 0; rw < rows; rw++) {
            for (int b = 0; b < nblk; b++)
                memcpy(src + (size_t)b * n,
                       br + ((size_t)rw * nblk + b) * n, (size_t)n * sizeof(float));
            memcpy(src + (size_t)nblk * n, px + (size_t)rw * n, (size_t)n * sizeof(float));
            k3_attn_res(y + (size_t)rw * n, src, fold, nsrc, n, eps);
        }
        report("attn_res", y, e, no);
        free(src); free(y);
    }
    free(px); free(br); free(fold); free(e); free(txt); free(ar);
}

/* The isolated recurrence. This is where the ordering bug lives: decay, then the
 * rank-one delta write, then read the ALREADY UPDATED state. Any permutation runs
 * cleanly and produces a wrong model, so it gets its own test at T=1 and T=8. */
static void t_recur(const char *dir, const char *file)
{
    char p[512]; snprintf(p, sizeof(p), "%s/%s.json", dir, file);
    char *txt = slurp(p); if (!txt) { g_fail++; return; }
    char *ar = NULL; jval *r = json_parse(txt, &ar);

    const int T = (int)num(r, "T", 0), H = (int)num(r, "H", 0);
    const int dk = (int)num(r, "d_k", 0), dv = (int)num(r, "d_v", dk);
    const float qs = (float)num(r, "q_scale", 1.0);
    int nq, nk, nv, na, nb, no, nso;
    float *q = arr(r, "q", &nq), *k = arr(r, "k", &nk), *v = arr(r, "v", &nv);
    float *al = arr(r, "alpha", &na), *bt = arr(r, "beta", &nb);
    float *eo = arr(r, "out", &no), *es = arr(r, "state_out", &nso);

    if (q && k && v && al && bt && eo && es && T && H && dk) {
        float *S = (float *)calloc((size_t)H * dk * dv, sizeof(float));
        float *out = (float *)malloc((size_t)T * H * dv * sizeof(float));
        float *qs_ = (float *)malloc((size_t)dk * sizeof(float));
        for (int t = 0; t < T; t++) {
            for (int h = 0; h < H; h++) {
                const size_t off = ((size_t)t * H + h) * dk;
                for (int i = 0; i < dk; i++) qs_[i] = q[off + i] * qs;   /* d_k^-0.5 */
                k3_kda_step(S + (size_t)h * dk * dv,
                            out + ((size_t)t * H + h) * dv,
                            qs_, k + off, v + off,
                            al + ((size_t)t * H + h) * dk,
                            bt[(size_t)t * H + h], dk, dv);
            }
        }
        char nm[32]; snprintf(nm, sizeof(nm), "%s_out", file);
        report(nm, out, eo, no);
        snprintf(nm, sizeof(nm), "%s_state", file);
        report(nm, S, es, nso);
        free(S); free(out); free(qs_);
    }
    free(q); free(k); free(v); free(al); free(bt); free(eo); free(es);
    free(txt); free(ar);
}

/* Router. The fixture's frozen bias reorders the top-k in 5 of 6 rows, so an engine
 * that ignored e_score_correction_bias, or that gathered the weights from the BIASED
 * scores, fails here rather than silently degrading. Indices are compared as SETS
 * because the reference uses topk(sorted=False), whose order is unspecified. */
static void t_router(const char *dir)
{
    char p[512]; snprintf(p, sizeof(p), "%s/router.json", dir);
    char *txt = slurp(p); if (!txt) { g_fail++; return; }
    char *ar = NULL; jval *r = json_parse(txt, &ar);

    int nw, nb, ni, nidx, nwt;
    float *W = arr(r, "gate_weight", &nw), *bias = arr(r, "bias", &nb);
    float *x = arr(r, "in", &ni);
    float *eidx = arr(r, "topk_idx", &nidx), *ewt = arr(r, "topk_weight", &nwt);
    const int K = (int)num(r, "top_k", 0), E = (int)num(r, "n_experts", 0);

    if (W && bias && x && eidx && ewt && K && E) {
        const int hidden = nw / E, rows = ni / hidden;
        int   *gi = (int   *)malloc((size_t)K * sizeof(int));
        float *gw = (float *)malloc((size_t)K * sizeof(float));
        int set_ok = 1; double worst_w = 0.0;

        for (int rw = 0; rw < rows; rw++) {
            k3_router(gi, gw, x + (size_t)rw * hidden, W, bias, hidden, E, K, 1, 1.0f);

            /* compare index SETS */
            for (int a = 0; a < K; a++) {
                int found = 0;
                for (int b = 0; b < K; b++)
                    if ((int)eidx[(size_t)rw * K + b] == gi[a]) { found = 1; break; }
                if (!found) { set_ok = 0;
                    printf("        row %d: C picked expert %d, reference did not\n", rw, gi[a]); }
            }
            /* match weights by expert id, since order is unspecified */
            for (int a = 0; a < K; a++) {
                for (int b = 0; b < K; b++) {
                    if ((int)eidx[(size_t)rw * K + b] != gi[a]) continue;
                    const double d = fabs((double)gw[a] - (double)ewt[(size_t)rw * K + b]);
                    const double tol = ATOL + RTOL * fabs((double)ewt[(size_t)rw * K + b]);
                    if (d / tol > worst_w) worst_w = d / tol;
                }
            }
        }
        if (set_ok && worst_w <= 1.0) {
            printf("  PASS  router         rows=%-4d k=%d  index sets match, "
                   "worst weight=%.2fx tol\n", rows, K, worst_w);
            g_pass++;
        } else {
            printf("  FAIL  router         index_sets=%s worst weight=%.2fx tol\n",
                   set_ok ? "ok" : "MISMATCH", worst_w);
            g_fail++;
        }
        free(gi); free(gw);
    }
    free(W); free(bias); free(x); free(eidx); free(ewt); free(txt); free(ar);
}

/* Gated MLA. The fixture now ships all eight weight tensors, so this is genuinely
 * reproducible. Watch for: the 192-wide head (128 nope + 64 unrotated rope), the
 * scale over 192 not 128, the single-head k_rope broadcast, and the gate applied
 * BEFORE o_proj with no norm. */
static void t_mla(const char *dir)
{
    char p[512]; snprintf(p, sizeof(p), "%s/mla.json", dir);
    char *txt = slurp(p); if (!txt) { g_fail++; return; }
    char *ar = NULL; jval *r = json_parse(txt, &ar);

    K3Cfg c; memset(&c, 0, sizeof c);
    c.qk_nope = (int)num(r, "qk_nope", 0);
    c.qk_rope = (int)num(r, "qk_rope", 0);
    c.kv_lora = (int)num(r, "kv_lora", 0);
    c.q_lora  = (int)num(r, "q_lora", 0);
    c.v_head  = (int)num(r, "v_head", 0);
    c.n_heads = (int)num(r, "n_heads", 0);
    c.rms_eps = (float)num(r, "rms_eps", 1e-5);

    int n_in, n_out, dum;
    float *x  = arr(r, "in", &n_in);
    float *eo = arr(r, "out", &n_out);
    /* Zeroed: wdt selects fp32 versus bf16 dispatch, and stack garbage there sends
     * fp32 fixture arrays into k3_matmul_bf16. That fails nondeterministically and
     * looks like an arithmetic bug in MLA rather than an initialisation bug here. */
    K3MlaW w; memset(&w, 0, sizeof w);
    w.q_a      = arr(r, "q_a_proj_weight", &dum);
    w.q_a_norm = arr(r, "q_a_layernorm_weight", &dum);
    w.q_b      = arr(r, "q_b_proj_weight", &dum);
    w.kv_a     = arr(r, "kv_a_proj_with_mqa_weight", &dum);
    w.kv_a_norm= arr(r, "kv_a_layernorm_weight", &dum);
    w.kv_b     = arr(r, "kv_b_proj_weight", &dum);
    w.o        = arr(r, "o_proj_weight", &dum);
    w.g        = arr(r, "g_proj_weight", &dum);

    if (x && eo && w.q_a && w.q_b && w.kv_a && w.kv_b && w.o) {
        int din[4] = {0};
        shape(r, "in", din, 4);
        const int T = din[1];
        c.hidden = din[2];
        float *scratch = (float *)malloc(k3_mla_scratch(&c, T) * sizeof(float));
        float *y = (float *)malloc((size_t)T * c.hidden * sizeof(float));
        if (scratch && y) {
            k3_mla(y, x, &w, &c, T, scratch);
            report("mla", y, eo, n_out);
            printf("        H=%d qh=%d (nope %d + rope %d) v=%d kv_lora=%d scale=%.6f\n",
                   c.n_heads, c.qk_nope + c.qk_rope, c.qk_nope, c.qk_rope,
                   c.v_head, c.kv_lora, 1.0 / sqrt((double)(c.qk_nope + c.qk_rope)));
        }
        free(scratch); free(y);
    }
    free(x); free(eo);
    free((void *)w.q_a); free((void *)w.q_a_norm); free((void *)w.q_b);
    free((void *)w.kv_a); free((void *)w.kv_a_norm); free((void *)w.kv_b);
    free((void *)w.o); free((void *)w.g);
    free(txt); free(ar);
}

/* Stable LatentMoE. The fixture drives SiTU into its caps and uses a routing bias
 * that genuinely reorders the top-k, so a wrong ordering (norming per expert instead
 * of on the aggregate, weighting the shared expert, routing on the latent instead of
 * the full width) fails here rather than degrading quietly. */
static void t_moe(const char *dir)
{
    char p[512]; snprintf(p, sizeof(p), "%s/moe.json", dir);
    char *txt = slurp(p); if (!txt) { g_fail++; return; }
    char *ar = NULL; jval *r = json_parse(txt, &ar);

    K3Cfg c; memset(&c, 0, sizeof c);
    c.hidden       = (int)num(r, "hidden", 0);
    c.latent       = (int)num(r, "latent", 0);
    c.moe_inter    = (int)num(r, "moe_inter", 0);
    c.n_experts    = (int)num(r, "n_experts", 0);
    c.topk         = (int)num(r, "top_k", 0);
    c.n_shared     = (int)num(r, "n_shared", 0);
    c.routed_scale = (float)num(r, "routed_scale", 1.0);
    c.moe_renorm   = (int)num(r, "renorm", 1);
    c.latent_norm  = (int)num(r, "latent_norm", 1);
    c.rms_eps      = (float)num(r, "rms_eps", 1e-5);
    c.situ_b1      = (float)num(r, "situ_b1", 4.0);
    c.situ_b2      = (float)num(r, "situ_b2", 25.0);

    int n_in, n_out, d;
    float *x  = arr(r, "in", &n_in);
    float *eo = arr(r, "out", &n_out);

    /* Zeroed, not merely assigned field by field: K3MoeW carries an optional expert
     * SOURCE, and a garbage src on an uninitialised stack struct is called as a
     * function pointer. */
    K3MoeW w; memset(&w, 0, sizeof w);
    w.gate        = arr(r, "gate_weight", &d);
    w.bias        = arr(r, "e_score_correction_bias", &d);
    w.down        = arr(r, "down_weight", &d);
    w.up          = arr(r, "up_weight", &d);
    w.latent_norm = arr(r, "norm_weight", &d);
    w.sh1         = arr(r, "shared_w1_weight", &d);
    w.sh3         = arr(r, "shared_w3_weight", &d);
    w.sh2         = arr(r, "shared_w2_weight", &d);

    /* routed experts arrive as experts_N_wK_weight; pack them contiguously */
    const size_t per13 = (size_t)c.moe_inter * c.latent;
    const size_t per2  = (size_t)c.latent * c.moe_inter;
    float *W1 = (float *)malloc(per13 * c.n_experts * sizeof(float));
    float *W3 = (float *)malloc(per13 * c.n_experts * sizeof(float));
    float *W2 = (float *)malloc(per2  * c.n_experts * sizeof(float));
    int packed = 1;
    for (int e = 0; e < c.n_experts && packed; e++) {
        char k1[64], k3[64], k2[64];
        snprintf(k1, sizeof k1, "experts_%d_w1_weight", e);
        snprintf(k3, sizeof k3, "experts_%d_w3_weight", e);
        snprintf(k2, sizeof k2, "experts_%d_w2_weight", e);
        float *a1 = arr(r, k1, &d), *a3 = arr(r, k3, &d), *a2 = arr(r, k2, &d);
        if (!a1 || !a3 || !a2) { packed = 0; free(a1); free(a3); free(a2); break; }
        memcpy(W1 + e * per13, a1, per13 * sizeof(float));
        memcpy(W3 + e * per13, a3, per13 * sizeof(float));
        memcpy(W2 + e * per2,  a2, per2  * sizeof(float));
        free(a1); free(a3); free(a2);
    }
    w.w1 = W1; w.w3 = W3; w.w2 = W2;

    if (x && eo && packed && w.gate && w.down && w.up && w.sh1) {
        int din[4] = {0}; shape(r, "in", din, 4);
        const int T = din[1];
        int   *idx = (int   *)malloc((size_t)c.topk * sizeof(int));
        float *wt  = (float *)malloc((size_t)c.topk * sizeof(float));
        float *sc  = (float *)malloc(k3_moe_scratch(&c) * sizeof(float));
        float *y   = (float *)malloc((size_t)T * c.hidden * sizeof(float));
        if (idx && wt && sc && y) {
            k3_moe(y, x, &w, &c, T, idx, wt, sc);
            report("moe", y, eo, n_out);
            printf("        hidden=%d latent=%d inter=%d experts=%d top%d shared=%d\n",
                   c.hidden, c.latent, c.moe_inter, c.n_experts, c.topk, c.n_shared);
        }
        free(idx); free(wt); free(sc); free(y);
    } else if (!packed) {
        printf("  FAIL  moe            could not pack expert weights from fixture\n");
        g_fail++;
    }
    free(x); free(eo); free(W1); free(W3); free(W2);
    free((void *)w.gate); free((void *)w.bias); free((void *)w.down); free((void *)w.up);
    free((void *)w.latent_norm); free((void *)w.sh1); free((void *)w.sh3); free((void *)w.sh2);
    free(txt); free(ar);
}

/* The full KDA layer. This is the last and hardest component before the decoder
 * layer: projections, three depthwise convs with fused SiLU, L2Norm on q/k only,
 * the shared low-rank decay, the per-head beta, the recurrence, the head-wise norm
 * and the gate in THAT order, then the output projection. Run at T=1 (the decode
 * path) and T=8 (where an ordering bug compounds). */
static void t_kda_layer(const char *dir, const char *file)
{
    char p[512]; snprintf(p, sizeof(p), "%s/%s.json", dir, file);
    char *txt = slurp(p); if (!txt) { g_fail++; return; }
    char *ar = NULL; jval *r = json_parse(txt, &ar);

    K3Cfg c; memset(&c, 0, sizeof c);
    c.kda_heads    = (int)num(r, "H", 0);
    c.kda_head_dim = (int)num(r, "d_k", 0);
    c.conv_k       = (int)num(r, "conv_k", 4);
    c.gate_lb      = (float)num(r, "lower_bound", -5.0);
    c.rms_eps      = (float)num(r, "rms_eps", 1e-5);

    int n_in, n_out, n_st, d;
    float *x  = arr(r, "in", &n_in);
    float *eo = arr(r, "out", &n_out);
    float *es = arr(r, "state_out", &n_st);

    K3KdaW w; memset(&w, 0, sizeof w);   /* see the note in t_mla: wdt must not be garbage */
    w.q = arr(r, "q_proj", &d);  w.k = arr(r, "k_proj", &d);  w.v = arr(r, "v_proj", &d);
    w.q_conv = arr(r, "q_conv", &d); w.k_conv = arr(r, "k_conv", &d);
    w.v_conv = arr(r, "v_conv", &d);
    w.f_a = arr(r, "f_a", &d);   w.f_b = arr(r, "f_b", &d);
    w.A_log = arr(r, "A_log", &d); w.dt_bias = arr(r, "dt_bias", &d);
    w.b = arr(r, "b_proj", &d);  w.g = arr(r, "g_proj", &d);
    w.o_norm = arr(r, "o_norm", &d); w.o = arr(r, "o_proj", &d);

    if (x && eo && w.q && w.f_b && w.A_log && w.o) {
        int din[4] = {0}; shape(r, "in", din, 4);
        const int T = din[1];
        c.hidden = din[2];
        const int P = c.kda_heads * c.kda_head_dim, hist = c.conv_k - 1;
        float *st = (float *)calloc((size_t)P * c.kda_head_dim
                                    + (size_t)3 * P * hist, sizeof(float));
        float *sc = (float *)malloc(k3_kda_scratch(&c, T) * sizeof(float));
        float *y  = (float *)malloc((size_t)T * c.hidden * sizeof(float));
        if (st && sc && y) {
            k3_kda_layer(y, x, &w, &c, T, st, sc);
            char nm[40]; snprintf(nm, sizeof nm, "%s_out", file);
            report(nm, y, eo, n_out);
            if (es) { snprintf(nm, sizeof nm, "%s_state", file);
                      report(nm, st, es, n_st); }
        }
        free(st); free(sc); free(y);
    }
    free(x); free(eo); free(es);
    free((void*)w.q); free((void*)w.k); free((void*)w.v);
    free((void*)w.q_conv); free((void*)w.k_conv); free((void*)w.v_conv);
    free((void*)w.f_a); free((void*)w.f_b); free((void*)w.A_log);
    free((void*)w.dt_bias); free((void*)w.b); free((void*)w.g);
    free((void*)w.o_norm); free((void*)w.o);
    free(txt); free(ar);
}

/* A whole decoder layer: the AttnRes wiring plus attention plus the MoE. This is the
 * last stop before the full model. What it actually exercises that nothing else does:
 * the aggregate REPLACING the layer input, the snapshot push, and the prefix_sum
 * reset at a block boundary. layer_kda is index 1 (not a boundary, so the running
 * residual survives); layer_mla is index 3 (also not a boundary here, block size 3
 * means boundaries are 0,3,6,9,12 -- so index 3 IS one). Between them both paths run. */
static float *pack_experts(jval *r, const char *fmt, int n, size_t per)
{
    float *W = (float *)malloc(per * n * sizeof(float));
    if (!W) return NULL;
    for (int e = 0; e < n; e++) {
        char key[80]; int d;
        snprintf(key, sizeof key, fmt, e);
        float *a = arr(r, key, &d);
        if (!a) { free(W); return NULL; }
        memcpy(W + (size_t)e * per, a, per * sizeof(float));
        free(a);
    }
    return W;
}

static void t_layer(const char *dir, const char *file)
{
    char p[512]; snprintf(p, sizeof(p), "%s/%s.json", dir, file);
    char *txt = slurp(p); if (!txt) { g_fail++; return; }
    char *ar = NULL; jval *r = json_parse(txt, &ar);

    const int li = (int)num(r, "layer_idx", 0);
    const int is_mla = boolean(r, "is_mla", 0);

    K3Cfg c; memset(&c, 0, sizeof c);
    c.hidden = (int)num(r, "hidden", 0);
    c.rms_eps = (float)num(r, "rms_eps", 1e-5);
    c.attn_res_block = (int)num(r, "attn_res_block_size", 3);
    c.n_layers = 13;
    c.kda_heads = 4; c.kda_head_dim = 16; c.conv_k = 4; c.gate_lb = -5.0f;
    c.n_heads = 4; c.q_lora = 64; c.kv_lora = 32;
    c.qk_nope = 24; c.qk_rope = 8; c.v_head = 16;
    c.n_experts = 8; c.topk = 2; c.n_shared = 2;
    c.latent = 64; c.moe_inter = 48; c.routed_scale = 1.0f;
    c.moe_renorm = 1; c.latent_norm = 1;
    c.situ_b1 = 4.0f; c.situ_b2 = 25.0f;
    c.first_dense = 1; c.dense_inter = 96;

    int n_in, n_out, n_bri, d;
    float *x   = arr(r, "in", &n_in);
    float *eo  = arr(r, "out", &n_out);
    float *bri = arr(r, "block_residual_in", &n_bri);

    K3KdaW kw; K3MlaW mw; K3MoeW ow; K3LayerW lw;
    memset(&kw, 0, sizeof kw); memset(&mw, 0, sizeof mw);
    memset(&ow, 0, sizeof ow); memset(&lw, 0, sizeof lw);
    lw.in_norm       = arr(r, "input_layernorm_weight", &d);
    lw.post_norm     = arr(r, "post_attention_layernorm_weight", &d);
    lw.attn_res_norm = arr(r, "self_attention_res_norm_weight", &d);
    lw.attn_res_proj = arr(r, "self_attention_res_proj_weight", &d);
    lw.mlp_res_norm  = arr(r, "mlp_res_norm_weight", &d);
    lw.mlp_res_proj  = arr(r, "mlp_res_proj_weight", &d);

    if (is_mla) {
        mw.q_a = arr(r,"self_attn_q_a_proj_weight",&d);
        mw.q_a_norm = arr(r,"self_attn_q_a_layernorm_weight",&d);
        mw.q_b = arr(r,"self_attn_q_b_proj_weight",&d);
        mw.kv_a = arr(r,"self_attn_kv_a_proj_with_mqa_weight",&d);
        mw.kv_a_norm = arr(r,"self_attn_kv_a_layernorm_weight",&d);
        mw.kv_b = arr(r,"self_attn_kv_b_proj_weight",&d);
        mw.o = arr(r,"self_attn_o_proj_weight",&d);
        mw.g = arr(r,"self_attn_g_proj_weight",&d);
        lw.mla = &mw;
    } else {
        kw.q = arr(r,"self_attn_q_proj_weight",&d);
        kw.k = arr(r,"self_attn_k_proj_weight",&d);
        kw.v = arr(r,"self_attn_v_proj_weight",&d);
        kw.q_conv = arr(r,"self_attn_q_conv1d_weight",&d);
        kw.k_conv = arr(r,"self_attn_k_conv1d_weight",&d);
        kw.v_conv = arr(r,"self_attn_v_conv1d_weight",&d);
        kw.f_a = arr(r,"self_attn_f_a_proj_weight",&d);
        kw.f_b = arr(r,"self_attn_f_b_proj_weight",&d);
        kw.A_log = arr(r,"self_attn_A_log",&d);
        kw.dt_bias = arr(r,"self_attn_dt_bias",&d);
        kw.b = arr(r,"self_attn_b_proj_weight",&d);
        kw.g = arr(r,"self_attn_g_proj_weight",&d);
        kw.o_norm = arr(r,"self_attn_o_norm_weight",&d);
        kw.o = arr(r,"self_attn_o_proj_weight",&d);
        lw.kda = &kw;
    }

    ow.gate = arr(r,"mlp_gate_weight",&d);
    ow.bias = arr(r,"mlp_e_score_correction_bias",&d);
    ow.down = arr(r,"mlp_down_weight",&d);
    ow.up   = arr(r,"mlp_up_weight",&d);
    ow.latent_norm = arr(r,"mlp_norm_weight",&d);
    ow.sh1 = arr(r,"mlp_shared_w1_weight",&d);
    ow.sh3 = arr(r,"mlp_shared_w3_weight",&d);
    ow.sh2 = arr(r,"mlp_shared_w2_weight",&d);
    ow.w1 = pack_experts(r,"mlp_experts_%d_w1_weight",c.n_experts,(size_t)c.moe_inter*c.latent);
    ow.w3 = pack_experts(r,"mlp_experts_%d_w3_weight",c.n_experts,(size_t)c.moe_inter*c.latent);
    ow.w2 = pack_experts(r,"mlp_experts_%d_w2_weight",c.n_experts,(size_t)c.latent*c.moe_inter);
    lw.moe = &ow;

    if (x && eo && bri && ow.w1 && ow.w2 && ow.w3 && lw.in_norm) {
        int din[4]={0}, dbr[4]={0};
        shape(r,"in",din,4); shape(r,"block_residual_in",dbr,4);
        const int T = din[1], nb_in = dbr[1];
        const int maxb = c.n_layers / c.attn_res_block + 2;

        float *h  = (float*)malloc((size_t)T*c.hidden*sizeof(float));
        float *br = (float*)calloc((size_t)T*maxb*c.hidden,sizeof(float));
        float *sc = (float*)malloc(k3_layer_scratch(&c,T)*sizeof(float));
        const int P = c.kda_heads*c.kda_head_dim;
        float *st = (float*)calloc((size_t)P*c.kda_head_dim + (size_t)3*P*(c.conv_k-1),
                                   sizeof(float));
        int nb = nb_in;
        if (h && br && sc && st) {
            memcpy(h, x, (size_t)T*c.hidden*sizeof(float));
            for (int t=0;t<T;t++)
                for (int b=0;b<nb_in;b++)
                    memcpy(br+((size_t)t*maxb+b)*c.hidden,
                           bri+((size_t)t*nb_in+b)*c.hidden,
                           (size_t)c.hidden*sizeof(float));
            k3_decoder_layer(h, br, &nb, &lw, &c, li, T, st, sc);
            char nm[40]; snprintf(nm,sizeof nm,"%s",file);
            report(nm, h, eo, n_out);
            printf("        layer %d (%s), blocks %d -> %d, boundary=%s\n",
                   li, is_mla?"MLA":"KDA", nb_in, nb,
                   (li % c.attn_res_block==0)?"YES, prefix_sum cleared":"no");
        }
        free(h); free(br); free(sc); free(st);
    }
    free(x); free(eo); free(bri);
    free((void*)ow.w1); free((void*)ow.w3); free((void*)ow.w2);
    free(txt); free(ar);
}

/* MXFP4 dequant, checked against REAL Kimi K3 checkpoint bytes. Every other fixture
 * uses synthetic values; this one cannot, because the point is to agree with how
 * Moonshot actually wrote the bytes. */
static void t_mxfp4(const char *dir)
{
    /* mxfp4.json sits BESIDE the ops/ directory, not inside it, because it is built
     * from released checkpoint bytes rather than from the reference implementation.
     * Both orderings are attempted. */
    char p[512];
    snprintf(p, sizeof(p), "%s/mxfp4.json", dir);
    char *txt = slurp_quiet(p);
    if (!txt) { snprintf(p, sizeof(p), "%s/../mxfp4.json", dir); txt = slurp_quiet(p); }
    if (!txt) {
        printf("  SKIP  mxfp4          fixture absent; run tools/fetch_mxfp4.py\n");
        g_skip++;
        return;
    }
    char *ar = NULL; jval *r = json_parse(txt, &ar);

    const int rows  = (int)num(r, "rows", 0);
    const int pcols = (int)num(r, "packed_cols", 0);
    const int grp   = (int)num(r, "group_size", 32);
    int np_, ns_, ne_;
    float *pf = arr(r, "packed", &np_);
    float *sf = arr(r, "scales", &ns_);
    float *ef = arr(r, "expected", &ne_);

    if (pf && sf && ef && rows && pcols) {
        unsigned char *P = (unsigned char *)malloc((size_t)np_);
        unsigned char *S = (unsigned char *)malloc((size_t)ns_);
        float *y = (float *)malloc((size_t)ne_ * sizeof(float));
        for (int i = 0; i < np_; i++) P[i] = (unsigned char)pf[i];
        for (int i = 0; i < ns_; i++) S[i] = (unsigned char)sf[i];

        k3_mxfp4_dequant(y, P, S, rows, pcols, grp);

        /* exact equality: dequantisation is a table lookup times a power of two, so
         * there is no rounding anywhere and anything but a bit-exact match is a bug */
        int bad = 0; double worst = 0.0; int at = -1;
        for (int i = 0; i < ne_; i++) {
            const double d = fabs((double)y[i] - (double)ef[i]);
            if (d > worst) { worst = d; at = i; }
            if (d != 0.0) bad++;
        }
        if (bad == 0) {
            printf("  PASS  mxfp4          %d rows x %d elems, EXACT on released checkpoint bytes\n",
                   rows, pcols * 2);
            g_pass++;
        } else {
            printf("  FAIL  mxfp4          %d of %d elements differ, worst %.7g at %d "
                   "(got %.7f want %.7f)\n", bad, ne_, worst, at, y[at], ef[at]);
            g_fail++;
        }
        free(P); free(S); free(y);
    }
    free(pf); free(sf); free(ef); free(txt); free(ar);
}

/* k3_matmul_bf16 must equal k3_matmul EXACTLY, not approximately.
 *
 * Both widen the same bf16 values to the same float32 values (a left shift by 16, which
 * is lossless), then accumulate in double in the same order with the same four partial
 * sums. So the only way they can differ is if one of them is wrong. Comparing with a
 * tolerance here would hide precisely the bugs worth catching: a wrong stride, a
 * dropped tail element, a mis-shifted widen.
 *
 * This test needs no fixture. It generates bf16 bit patterns directly, which also means
 * it covers values a Gaussian sample would never produce - the checkpoint contains
 * denormals and very large exponents, and the widen must handle them by construction
 * rather than by luck.
 */
static void t_matmul_bf16(void)
{
    const int in = 257, out = 129;            /* deliberately not multiples of 4 */
    uint16_t *Wb = (uint16_t *)malloc((size_t)in * out * sizeof(uint16_t));
    float    *Wf = (float *)malloc((size_t)in * out * sizeof(float));
    float    *x  = (float *)malloc((size_t)in * sizeof(float));
    float    *ya = (float *)malloc((size_t)out * sizeof(float));
    float    *yb = (float *)malloc((size_t)out * sizeof(float));
    if (!Wb || !Wf || !x || !ya || !yb) { printf("  FAIL  matmul_bf16 (alloc)\n"); g_fail++; return; }

    unsigned s = 0xC0FFEEu;
    for (size_t i = 0; i < (size_t)in * out; i++) {
        s ^= s << 13; s ^= s >> 17; s ^= s << 5;
        /* Any 16-bit pattern EXCEPT the NaN/Inf exponent, which would make every
         * comparison trivially NaN and prove nothing. */
        uint16_t h = (uint16_t)(s >> 8);
        if (((h >> 7) & 0xFF) == 0xFF) h &= 0x7F7Fu;
        Wb[i] = h;
        Wf[i] = k3_bf16f(h);                  /* the SAME value, stored wide */
    }
    for (int i = 0; i < in; i++) {
        s ^= s << 13; s ^= s >> 17; s ^= s << 5;
        x[i] = (float)(s >> 8) / 8388608.0f - 1.0f;
    }

    k3_matmul(ya, x, Wf, in, out);
    k3_matmul_bf16(yb, x, Wb, in, out);

    int bad = 0;
    for (int o = 0; o < out; o++) {
        union { float f; uint32_t u; } a, b;
        a.f = ya[o]; b.f = yb[o];
        if (a.u != b.u) bad++;
    }
    if (bad) { printf("  FAIL  matmul_bf16   %d/%d rows differ from the fp32 path\n", bad, out); g_fail++; }
    else     { printf("  PASS  matmul_bf16   n=%d    bit-identical to k3_matmul\n", out); g_pass++; }
    free(Wb); free(Wf); free(x); free(ya); free(yb);
}

/* Streamed MoE: k3_moe with a K3ExpertSrc must equal, bit for bit, the per-expert loop
 * it replaced (three k3_matmul_mxfp4 calls per expert, summed in top-k order). Random
 * MXFP4 experts, shapes chosen so the batched path splits rows into several blocks. */
typedef struct { K3ExpertSrc src; unsigned char *mem; size_t per; int I, L; } MemExperts;

static int memx_get(K3ExpertSrc *self, int layer, int e, K3ExpertQ *q)
{
    MemExperts *m = (MemExperts *)self;
    (void)layer;
    const size_t p13 = (size_t)m->I * m->L / 2, s13 = (size_t)m->I * m->L / 32;
    unsigned char *b = m->mem + (size_t)e * m->per;
    q->p1 = b;                  q->s1 = b + p13;
    q->p3 = b + p13 + s13;      q->s3 = q->p3 + p13;
    q->p2 = q->s3 + s13;        q->s2 = q->p2 + p13;
    q->ilv = 0;
    return 0;
}

static void t_moe_streamed(void)
{
    K3Cfg c; memset(&c, 0, sizeof c);
    c.hidden = 96; c.latent = 128; c.moe_inter = 160; c.n_experts = 12; c.topk = 5;
    c.n_shared = 1; c.moe_renorm = 1; c.routed_scale = 1.0f; c.latent_norm = 1;
    c.rms_eps = 1e-5f; c.situ_b1 = 4.0f; c.situ_b2 = 25.0f;
    const int E = c.hidden, L = c.latent, I = c.moe_inter, NE = c.n_experts, T = 3;
    const size_t per = 3 * ((size_t)I * L / 2 + (size_t)I * L / 32);

    unsigned s = 0xBADC0DEu;
#define RNG() (s ^= s << 13, s ^= s >> 17, s ^= s << 5, s)
    MemExperts mx; memset(&mx, 0, sizeof mx);
    mx.src.get = memx_get; mx.per = per; mx.I = I; mx.L = L;
    mx.mem = (unsigned char *)malloc(per * NE);
    for (size_t i = 0; i < per * NE; i++) mx.mem[i] = (unsigned char)(RNG() >> 11);
    for (int e = 0; e < NE; e++) {                  /* keep scales in a sane range */
        K3ExpertQ q; memx_get(&mx.src, 0, e, &q);
        unsigned char *sc[3] = { (unsigned char *)q.s1, (unsigned char *)q.s3,
                                 (unsigned char *)q.s2 };
        for (int m = 0; m < 3; m++)
            for (int i = 0; i < I * L / 32; i++) sc[m][i] = (unsigned char)(120 + RNG() % 8);
    }
    float *fv = (float *)malloc(sizeof(float) * ((size_t)NE * E + NE + L + 2 * (size_t)L * E
                                                 + 3 * (size_t)I * E + (size_t)T * E));
    float *gate = fv, *bias = gate + NE * E, *lnorm = bias + NE, *down = lnorm + L;
    float *up = down + (size_t)L * E, *sh = up + (size_t)E * L, *x = sh + 3 * (size_t)I * E;
    for (size_t i = 0; i < (size_t)NE * E + NE + L + 2 * (size_t)L * E + 3 * (size_t)I * E
                           + (size_t)T * E; i++)
        fv[i] = ((float)(RNG() >> 8) / 8388608.0f - 1.0f) * 0.2f;
    for (int i = 0; i < L; i++) lnorm[i] += 1.0f;

    K3MoeW w; memset(&w, 0, sizeof w);
    w.gate = gate; w.bias = bias; w.latent_norm = lnorm; w.down = down; w.up = up;
    w.sh1 = sh; w.sh3 = sh + (size_t)I * E; w.sh2 = sh + 2 * (size_t)I * E;
    w.src = &mx.src;

    float *got = (float *)malloc(sizeof(float) * T * E);
    float *want = (float *)malloc(sizeof(float) * T * E);
    float *sc = (float *)malloc(k3_moe_scratch(&c) * sizeof(float));
    int idx[K3_MAX_TOPK]; float wt[K3_MAX_TOPK];
    k3_moe(got, x, &w, &c, T, idx, wt, sc);

    float *z = (float *)malloc(sizeof(float) * (3 * (size_t)L + 6 * (size_t)I + E));
    float *acc = z + L, *edn = acc + L, *gu = edn + L, *act = gu + 2 * I;
    float *sgu = act + I, *sdn = sgu + 2 * I + I;
    for (int t = 0; t < T; t++) {
        const float *xt = x + (size_t)t * E;
        float *ot = want + (size_t)t * E;
        k3_router(idx, wt, xt, gate, bias, E, NE, c.topk, c.moe_renorm, c.routed_scale);
        k3_matmul(z, xt, down, E, L);
        for (int i = 0; i < L; i++) acc[i] = 0.0f;
        for (int j = 0; j < c.topk; j++) {
            K3ExpertQ q; memx_get(&mx.src, 0, idx[j], &q);
            k3_matmul_mxfp4(gu,     z, q.p1, q.s1, L, I, K3_MXFP4_GROUP);
            k3_matmul_mxfp4(gu + I, z, q.p3, q.s3, L, I, K3_MXFP4_GROUP);
            k3_situ_glu(act, gu, I, c.situ_b1, c.situ_b2);
            k3_matmul_mxfp4(edn, act, q.p2, q.s2, I, L, K3_MXFP4_GROUP);
            for (int i = 0; i < L; i++) acc[i] += wt[j] * edn[i];
        }
        k3_rmsnorm(acc, acc, lnorm, L, c.rms_eps);
        k3_matmul(ot, acc, up, L, E);
        k3_matmul(sgu, xt, w.sh1, E, I);
        k3_matmul(sgu + I, xt, w.sh3, E, I);
        k3_situ_glu(sgu + 2 * I, sgu, I, c.situ_b1, c.situ_b2);
        k3_matmul(sdn, sgu + 2 * I, w.sh2, I, E);
        for (int i = 0; i < E; i++) ot[i] += sdn[i];
    }
#undef RNG
    const int same = memcmp(got, want, sizeof(float) * T * E) == 0;
    if (same) { printf("  PASS  moe_streamed  n=%d    bit-identical to the per-expert loop\n", T * E); g_pass++; }
    else      { printf("  FAIL  moe_streamed  batched experts differ from the per-expert loop\n"); g_fail++; }
    free(mx.mem); free(fv); free(got); free(want); free(sc); free(z);
}

/* Interleaved MXFP4 rows must give k3_matmul_mxfp4's result bit for bit; `in` has full
 * 128-blocks, a 64-chunk and a 16 tail so every kernel section runs. */
static void t_mxfp4_ilv(void)
{
    const int in = 3 * 128 + 64 + 48, rows = 97, G = K3_MXFP4_GROUP;
    const size_t pb = (size_t)rows * in / 2, sb = (size_t)rows * ((in + G - 1) / G);
    unsigned char *P = (unsigned char *)malloc(pb), *Q = (unsigned char *)malloc(pb);
    unsigned char *S = (unsigned char *)malloc(sb);
    float *x = (float *)malloc(in * sizeof(float));
    float *ya = (float *)malloc(rows * sizeof(float)), *yb = (float *)malloc(rows * sizeof(float));
    unsigned s = 0x5EEDu;
#define RNG() (s ^= s << 13, s ^= s >> 17, s ^= s << 5, s)
    for (size_t i = 0; i < pb; i++) P[i] = (unsigned char)(RNG() >> 9);
    for (size_t i = 0; i < sb; i++) S[i] = (unsigned char)(118 + RNG() % 12);
    for (int i = 0; i < in; i++) x[i] = (float)(RNG() >> 8) / 8388608.0f - 1.0f;
#undef RNG
    memcpy(Q, P, pb);
    k3_matmul_mxfp4(ya, x, P, S, in, rows, G);
    int ok;
    if (k3_mxfp4_interleave(Q, rows, in, G, K3_MX_F32)) {
        k3_matmul_mxfp4_ilv(yb, x, Q, S, in, rows, G, K3_MX_F32);
        ok = memcmp(ya, yb, rows * sizeof(float)) == 0 && memcmp(P, Q, pb) != 0;
        printf("  %s  mxfp4_ilv     n=%d    interleaved rows %s\n", ok ? "PASS" : "FAIL",
               rows, ok ? "bit-identical to checkpoint order" : "DIFFER");
    } else {
        ok = memcmp(P, Q, pb) == 0;
        printf("  %s  mxfp4_ilv     no interleaved kernel in this build, bytes %s\n",
               ok ? "PASS" : "FAIL", ok ? "untouched" : "CHANGED");
    }
    if (ok) g_pass++; else g_fail++;

    /* bf16 activations: both layouts agree to the bit, and both are the fp32 product
     * of the dequantised weights with x rounded to bf16, up to fp32 summation order */
    if (k3_act_bf16_supported()) {
        float *W = (float *)malloc((size_t)rows * in * sizeof(float));
        float *xr = (float *)malloc(in * sizeof(float));
        float *yc = (float *)malloc(rows * sizeof(float));
        k3_mxfp4_dequant(W, P, S, rows, in / 2, G);
        for (int i = 0; i < in; i++) {
            union { float f; uint32_t u; } v = { x[i] };
            v.u = (v.u + 0x7FFFu + ((v.u >> 16) & 1u)) & 0xFFFF0000u;
            xr[i] = v.f;
        }
        k3_matmul(yc, xr, W, in, rows);
        memcpy(Q, P, pb);
        k3_act_bf16 = K3_BF16_ALL;
        k3_matmul_mxfp4(ya, x, P, S, in, rows, G);
        const int lay = k3_mxfp4_interleave(Q, rows, in, G, K3_MX_BF16);
        if (lay) k3_matmul_mxfp4_ilv(yb, x, Q, S, in, rows, G, K3_MX_BF16);
        k3_act_bf16 = 0;
        double worst = 0.0;
        for (int r = 0; r < rows; r++) {
            const double d = fabs((double)ya[r] - yc[r]) / (fabs((double)yc[r]) + 1e-3);
            if (d > worst) worst = d;
        }
        ok = lay && memcmp(ya, yb, rows * sizeof(float)) == 0 && worst < 1e-5;
        printf("  %s  mxfp4_bf16    n=%d    layouts %s, rel diff to fp32 of bf16 x %.1e\n",
               ok ? "PASS" : "FAIL", rows, lay && !memcmp(ya, yb, rows * sizeof(float))
               ? "bit-identical" : "DIFFER", worst);
        if (ok) g_pass++; else g_fail++;
        free(W); free(xr); free(yc);
    }
    free(P); free(Q); free(S); free(x); free(ya); free(yb);
}

/* bf16 activations on bf16 weights: the fp32 matmul of the same weights with x rounded
 * to bf16, up to fp32 summation order; the one-rank gather rounds the same way. */
static void t_bf16_act(void)
{
    if (!k3_act_bf16_supported()) {
        printf("  PASS  bf16_act      not built with AVX512-BF16, mode unavailable\n");
        g_pass++;
        return;
    }
    const int in = 7168 + 40, out = 77;
    uint16_t *Wb = (uint16_t *)malloc((size_t)in * out * sizeof(uint16_t));
    float *Wf = (float *)malloc((size_t)in * out * sizeof(float));
    float *x = (float *)malloc(in * sizeof(float)), *xr = (float *)malloc(in * sizeof(float));
    float *ya = (float *)malloc(out * sizeof(float)), *yb = (float *)malloc(out * sizeof(float));
    unsigned s = 0xB16Fu;
#define RNG() (s ^= s << 13, s ^= s >> 17, s ^= s << 5, s)
    for (size_t i = 0; i < (size_t)in * out; i++) {
        union { float f; uint32_t u; } v = { (float)(RNG() >> 8) / 8388608.0f - 1.0f };
        Wb[i] = (uint16_t)(v.u >> 16);
        Wf[i] = k3_bf16f(Wb[i]);
    }
    for (int i = 0; i < in; i++) {
        union { float f; uint32_t u; } v = { (float)(RNG() >> 8) / 8388608.0f - 1.0f };
        x[i] = v.f;
        v.u = (v.u + 0x7FFFu + ((v.u >> 16) & 1u)) & 0xFFFF0000u;
        xr[i] = v.f;
    }
#undef RNG
    k3_matmul(ya, xr, Wf, in, out);
    k3_act_bf16 = K3_BF16_ALL;
    k3_matmul_bf16(yb, x, Wb, in, out);
    float g[5] = { x[0], x[1], x[2], x[3], x[4] };
    const K3Seg sg = { g, 5, 1, 0 };
    k3_tp_gather(&sg, 1);
    k3_act_bf16 = 0;
    double worst = 0.0;
    for (int o = 0; o < out; o++) {
        double mag = 0.0;                   /* summation-order error scales with sum |w x| */
        for (int i = 0; i < in; i++) mag += fabs((double)Wf[(size_t)o * in + i] * xr[i]);
        const double d = fabs((double)ya[o] - yb[o]) / mag;
        if (d > worst) worst = d;
    }
    const int gok = !memcmp(g, xr, sizeof g);
    const int ok = worst < 1e-6 && gok;
    printf("  %s  bf16_act      n=%d    rel diff %.1e to fp32 of bf16 x, gather %s\n",
           ok ? "PASS" : "FAIL", out, worst, gok ? "rounds" : "DOES NOT ROUND");
    if (ok) g_pass++; else g_fail++;
    free(Wb); free(Wf); free(x); free(xr); free(ya); free(yb);
}

int main(int argc, char **argv)
{
    const char *dir = (argc > 1) ? argv[1] : "../fixtures/ops";
    printf("Kimi K3 C ops, validated against the pure-torch reference\n");
    printf("fixtures: %s\n", dir);

    /* The manifest is the contract. Take its tolerances rather than hardcoded ones, and say out
     * loud which ones are in force so a future loosening cannot happen silently. */
    {
        char mp[512]; snprintf(mp, sizeof mp, "%s/MANIFEST.json", dir);
        char *mtxt = slurp_quiet(mp);
        if (!mtxt) {
            printf("tolerance: MANIFEST.json ABSENT, falling back to atol=%.1e rtol=%.1e\n\n",
                   (double)ATOL, (double)RTOL);
            g_skip++;
        } else {
            char *mar = NULL; jval *m = json_parse(mtxt, &mar);
            jval *tolo = m ? json_get(m, "tolerance") : NULL;
            const double fa = tolo ? num(tolo, "fp32_abs", ATOL) : ATOL;
            const double fr = tolo ? num(tolo, "fp32_rel", RTOL) : RTOL;
            ATOL = (float)fa; RTOL = (float)fr;
            printf("tolerance: atol=%.1e rtol=%.1e  (from MANIFEST.json)\n\n", fa, fr);
            free(mtxt); free(mar);
        }
    }

    t_rmsnorm(dir);
    t_situ(dir);
    t_shortconv(dir);
    t_decay(dir);
    t_recur(dir, "kda_recur1");
    t_recur(dir, "kda_recur8");
    t_router(dir);
    t_mla(dir);
    t_moe(dir);
    t_moe_streamed();
    t_mxfp4(dir);
    t_mxfp4_ilv();
    t_matmul_bf16();
    t_bf16_act();
    t_kda_layer(dir, "kda_layer1");
    t_kda_layer(dir, "kda_layer8");
    t_layer(dir, "layer_kda");
    t_layer(dir, "layer_mla");
    t_attnres(dir);

    printf("\n%d passed, %d failed, %d skipped\n", g_pass, g_fail, g_skip);
    if (g_skip)
        printf("SUITE INCOMPLETE: %d test(s) did not run. A skip is not a pass.\n", g_skip);
    return (g_fail || g_skip) ? 1 : 0;
}
